version: '3.8'

volumes:
  task_database_data:
networks:
  task_network:
    driver: bridge

services:
  #  task_database:
  #    container_name: task_database
  #    restart: always
  #    image: mysql:8.0
  #    volumes:
  #      - ./mysql/:/docker-entrypoint-initdb.d/
  #    healthcheck:
  #      test:
  #        [
  #          "CMD-SHELL",
  #          "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD",
  #        ]
  #      interval: 5s
  #      timeout: 20s
  #      retries: 30
  #    environment:
  #      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  #      MYSQL_DATABASE: ${MYSQL_DB_NAME}
  #      MYSQL_USER: ${MYSQL_USER}
  #      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #      MYSQL_PORT: ${MYSQL_PORT}
  #    ports:
  #      - ${MYSQL_PORT}:${MYSQL_PORT}
  #    expose:
  #      - ${MYSQL_PORT}
  #    networks:
  #      - task_network
  #    command: --init-file /docker-entrypoint-initdb.d/data.sql

  task_backend_app:
    container_name: task_backend_app
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - ./:/home/node/app
    networks:
      - task_network
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
